2025-05-03 16:19:57 - web.app - ERROR - Erro na execução da aplicação: 'dict' object has no attribute 'indicators'
2025-05-03 18:53:37 - src.services.cvm_api - ERROR - Erro ao obter dados da CVM para 54.776.432/0001-18: HTTPSConnectionPool(host='api.cvm.gov.br', port=443): Max retries exceeded with url: /fundos/54.776.432/0001-18/rentabilidade?dataInicial=2020-05-04&dataFinal=2025-05-03 (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7f5db24b50c0>: Failed to resolve 'api.cvm.gov.br' ([Errno -2] Name or service not known)"))
2025-05-03 18:58:29 - src.services.cvm_api - ERROR - Erro ao obter dados da CVM para 54.776.432/0001-18: HTTPSConnectionPool(host='api.cvm.gov.br', port=443): Max retries exceeded with url: /fundos/54.776.432/0001-18/rentabilidade?dataInicial=2020-05-04&dataFinal=2025-05-03 (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7f5db24b29e0>: Failed to resolve 'api.cvm.gov.br' ([Errno -2] Name or service not known)"))
2025-05-03 18:59:53 - src.services.cvm_api - ERROR - Erro ao obter dados da CVM para 54.776.432/0001-18: HTTPSConnectionPool(host='api.cvm.gov.br', port=443): Max retries exceeded with url: /fundos/54.776.432/0001-18/rentabilidade?dataInicial=2020-05-04&dataFinal=2025-05-03 (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7f5db24b57e0>: Failed to resolve 'api.cvm.gov.br' ([Errno -2] Name or service not known)"))
2025-05-03 19:02:48 - src.services.cvm_api - ERROR - Erro ao obter dados da CVM para 54.776.432/0001-18: HTTPSConnectionPool(host='api.cvm.gov.br', port=443): Max retries exceeded with url: /fundos/54.776.432/0001-18/rentabilidade?dataInicial=2020-05-04&dataFinal=2025-05-03 (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7f5db25cce80>: Failed to resolve 'api.cvm.gov.br' ([Errno -2] Name or service not known)"))
2025-05-03 19:04:12 - src.services.cvm_api - ERROR - Erro ao obter dados da CVM para 54.776.432/0001-18: HTTPSConnectionPool(host='api.cvm.gov.br', port=443): Max retries exceeded with url: /fundos/54.776.432/0001-18/rentabilidade?dataInicial=2020-05-04&dataFinal=2025-05-03 (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7f5db24c4160>: Failed to resolve 'api.cvm.gov.br' ([Errno -2] Name or service not known)"))
2025-05-03 19:04:14 - src.services.cvm_api - ERROR - Erro ao obter dados da CVM para 54.776.432/0001-18: HTTPSConnectionPool(host='api.cvm.gov.br', port=443): Max retries exceeded with url: /fundos/54.776.432/0001-18/rentabilidade?dataInicial=2020-05-04&dataFinal=2025-05-03 (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7f5db24c4c70>: Failed to resolve 'api.cvm.gov.br' ([Errno -2] Name or service not known)"))
